### ISSUE TITLE
"KeyError: '\\s'"

### ISSUE THREAD

**Issue by justjokiing** [DoubleThreatSecurity/Scylla#3]
I am kind of new to linux but I have been messing on Parrot OS for a couple months now. I get this error when I put in the command "python3 scylla.py --help":

Traceback (most recent call last):
  File "/usr/lib/python3.7/sre_parse.py", line 1015, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scylla.py", line 43, in <module>
    import pythonwhois
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/__init__.py", line 1, in <module>
    from . import net, parse
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 363, in <module>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex
    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.7/sre_parse.py", line 1018, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0

Hopefully it is a quick fix and sorry if it is something dumb. Thank you in advanced ;)

**Comment by josh0xA** [comment]
Hey man. Scylla is developed in Python3.6. You are using 3.7. Urllib is not configured properly for 3.7. I would recommend uninstalling 3.7 and install 3.6 so you can run the program. Hope this helps.

**Comment by justjokiing** [comment]
Would that affect my other packages?
