### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 0verdark** [DoubleThreatSecurity/Scylla#7]
**sudo python3 scylla.py --help**

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scylla.py", line 41, in <module>
    import pythonwhois
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/__init__.py", line 1, in <module>
    from . import net, parse
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <module>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex
    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.8/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0
```

**What does this mean? and how to fix this issue.**

**Comment by Bobpick** [comment]
I too have this error

**Comment by JustinLongnecker** [comment]
I have this error as well, has there been a fix released?

**Comment by josh0xA** [comment]
Hey. Scylla was written in python3.6. Please use this version until I re-program it in 3.8.
