### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by highrider0602** [DoubleThreatSecurity/Scylla#9]
From following instructions this is the README.md, didn't have any errors during install of requirements.txt, but when I ran "python3 scylla.py --help" and also tried "python scylla.py --help" minus the quotes, and both times I get the same error below

so this is what I get when I run the tool

Traceback (most recent call last):
  File "/usr/lib/python3.9/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Scylla/scylla.py", line 41, in <module>
    import pythonwhois
  File "/usr/local/lib/python3.9/dist-packages/pythonwhois/__init__.py", line 1, in <module>
    from . import net, parse
  File "/usr/local/lib/python3.9/dist-packages/pythonwhois/parse.py", line 363, in <module>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.9/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.9/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex
    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.9/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.9/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.9/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0
higrider187#

**Comment by JudeSavio** [comment]
Some sources have advised to use import regex as re instead of just re. Hope this helps, but didn't get the issue resolved for me

**Comment by Paresh-Maheshwari** [comment]
Same problem in my terminal

**Comment by Paresh-Maheshwari** [comment]
When I was run python3 scylla.py --help this code . Then show me

Traceback (most recent call last):
  File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scylla.py", line 41, in <module>
    import pythonwhois
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/__init__.py", line 1, in <module>
    from . import net, parse
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <module>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex
    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.8/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0

**Comment by JudeSavio** [comment]
Try downgrading to python 3.6

**Comment by Paresh-Maheshwari** [comment]
python3 --version
Python 3.8.6


This is my python version

**Comment by Paresh-Maheshwari** [comment]
> Try downgrading to python 3.6 if you have a higher version. Hope it helps

I am using latest version of python

python3 --version
Python 3.8.6

**Comment by JudeSavio** [comment]
Yeah some of the  payckages are meant to work with python 3.6. I am attaching the response from the owner of this repository for your reference 

"Hey man. Scylla is developed in Python3.6. You are using 3.7. Urllib is not configured properly for 3.7. I would recommend uninstalling 3.7 and install 3.6 so you can run the program. Hope this helps."

The script won't work in the latest version. You'll have to downgradde to 3.6 . I'd suggest you to create a virtual environment with 3.6 and then running the necessary steps. Hope it helps

**Comment by rooted-cyber** [comment]
![Screenshot_2021-02-03-18-18-17-24_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/50019150/106750161-7a948200-664d-11eb-8519-c4dc1e20b8f1.png)
sahi to hai

**Comment by highrider0602** [comment]
> Yeah some of the packages are meant to work with python 3.6. I am attaching the response from the owner of this repository for your reference
> 
> "Hey man. Scylla is developed in Python3.6. You are using 3.7. Urllib is not configured properly for 3.7. I would recommend uninstalling 3.7 and install 3.6 so you can run the program. Hope this helps."
> 
> The script won't work in the latest version. You'll have to downgrade to 3.6 . I'd suggest you to create a virtual environment with 3.6 and then running the necessary steps. Hope it helps

thanks for the help, got it working!

**Comment by josh0xA** [comment]
I don't even work on it anymore, to be honest. I made it in one night on my
MacBook with a bunch of outdated and misconfigured packages. Appreciate you
reaching out. If you wanna excel Scylla and make it really good we can talk
about putting together a dev team and seriously working on it. Let me know.

Kind regards,
Josh Schiavone

**Comment by JudeSavio** [comment]
Hey Josh,

It's great to hear from you, mate. Yeah I would love to help you in
building Scylla further, but in all honesty I'm just a beginner in the
security domain but I am eager as ever. Let me know if you have plans to
round up a team. I am happy to contribute to scylla. Thanks.

Kind regards,
Jude Savio
